export const COUNTRY_CODES = [
  { value: '+1', label: 'United States (+1)', country: 'US' },
  { value: '+1', label: 'Canada (+1)', country: 'CA' },
  { value: '+7', label: 'Russia (+7)', country: 'RU' },
  { value: '+7', label: 'Kazakhstan (+7)', country: 'KZ' },
  { value: '+20', label: 'Egypt (+20)', country: 'EG' },
  { value: '+27', label: 'South Africa (+27)', country: 'ZA' },
  { value: '+30', label: 'Greece (+30)', country: 'GR' },
  { value: '+31', label: 'Netherlands (+31)', country: 'NL' },
  { value: '+32', label: 'Belgium (+32)', country: 'BE' },
  { value: '+33', label: 'France (+33)', country: 'FR' },
  { value: '+34', label: 'Spain (+34)', country: 'ES' },
  { value: '+36', label: 'Hungary (+36)', country: 'HU' },
  { value: '+39', label: 'Italy (+39)', country: 'IT' },
  { value: '+40', label: 'Romania (+40)', country: 'RO' },
  { value: '+41', label: 'Switzerland (+41)', country: 'CH' },
  { value: '+43', label: 'Austria (+43)', country: 'AT' },
  { value: '+44', label: 'United Kingdom (+44)', country: 'GB' },
  { value: '+45', label: 'Denmark (+45)', country: 'DK' },
  { value: '+46', label: 'Sweden (+46)', country: 'SE' },
  { value: '+47', label: 'Norway (+47)', country: 'NO' },
  { value: '+48', label: 'Poland (+48)', country: 'PL' },
  { value: '+49', label: 'Germany (+49)', country: 'DE' },
  { value: '+51', label: 'Peru (+51)', country: 'PE' },
  { value: '+52', label: 'Mexico (+52)', country: 'MX' },
  { value: '+53', label: 'Cuba (+53)', country: 'CU' },
  { value: '+54', label: 'Argentina (+54)', country: 'AR' },
  { value: '+55', label: 'Brazil (+55)', country: 'BR' },
  { value: '+56', label: 'Chile (+56)', country: 'CL' },
  { value: '+57', label: 'Colombia (+57)', country: 'CO' },
  { value: '+58', label: 'Venezuela (+58)', country: 'VE' },
  { value: '+60', label: 'Malaysia (+60)', country: 'MY' },
  { value: '+61', label: 'Australia (+61)', country: 'AU' },
  { value: '+62', label: 'Indonesia (+62)', country: 'ID' },
  { value: '+63', label: 'Philippines (+63)', country: 'PH' },
  { value: '+64', label: 'New Zealand (+64)', country: 'NZ' },
  { value: '+65', label: 'Singapore (+65)', country: 'SG' },
  { value: '+66', label: 'Thailand (+66)', country: 'TH' },
  { value: '+81', label: 'Japan (+81)', country: 'JP' },
  { value: '+82', label: 'South Korea (+82)', country: 'KR' },
  { value: '+84', label: 'Vietnam (+84)', country: 'VN' },
  { value: '+86', label: 'China (+86)', country: 'CN' },
  { value: '+90', label: 'Turkey (+90)', country: 'TR' },
  { value: '+91', label: 'India (+91)', country: 'IN' },
  { value: '+92', label: 'Pakistan (+92)', country: 'PK' },
  { value: '+93', label: 'Afghanistan (+93)', country: 'AF' },
  { value: '+94', label: 'Sri Lanka (+94)', country: 'LK' },
  { value: '+95', label: 'Myanmar (+95)', country: 'MM' },
  { value: '+98', label: 'Iran (+98)', country: 'IR' },
  { value: '+212', label: 'Morocco (+212)', country: 'MA' },
  { value: '+213', label: 'Algeria (+213)', country: 'DZ' },
  { value: '+216', label: 'Tunisia (+216)', country: 'TN' },
  { value: '+218', label: 'Libya (+218)', country: 'LY' },
  { value: '+220', label: 'Gambia (+220)', country: 'GM' },
  { value: '+221', label: 'Senegal (+221)', country: 'SN' },
  { value: '+222', label: 'Mauritania (+222)', country: 'MR' },
  { value: '+223', label: 'Mali (+223)', country: 'ML' },
  { value: '+224', label: 'Guinea (+224)', country: 'GN' },
  { value: '+225', label: 'Ivory Coast (+225)', country: 'CI' },
  { value: '+226', label: 'Burkina Faso (+226)', country: 'BF' },
  { value: '+227', label: 'Niger (+227)', country: 'NE' },
  { value: '+228', label: 'Togo (+228)', country: 'TG' },
  { value: '+229', label: 'Benin (+229)', country: 'BJ' },
  { value: '+230', label: 'Mauritius (+230)', country: 'MU' },
  { value: '+231', label: 'Liberia (+231)', country: 'LR' },
  { value: '+232', label: 'Sierra Leone (+232)', country: 'SL' },
  { value: '+233', label: 'Ghana (+233)', country: 'GH' },
  { value: '+234', label: 'Nigeria (+234)', country: 'NG' },
  { value: '+235', label: 'Chad (+235)', country: 'TD' },
  { value: '+236', label: 'Central African Republic (+236)', country: 'CF' },
  { value: '+237', label: 'Cameroon (+237)', country: 'CM' },
  { value: '+238', label: 'Cape Verde (+238)', country: 'CV' },
  { value: '+239', label: 'São Tomé and Príncipe (+239)', country: 'ST' },
  { value: '+240', label: 'Equatorial Guinea (+240)', country: 'GQ' },
  { value: '+241', label: 'Gabon (+241)', country: 'GA' },
  { value: '+242', label: 'Republic of the Congo (+242)', country: 'CG' },
  { value: '+243', label: 'Democratic Republic of the Congo (+243)', country: 'CD' },
  { value: '+244', label: 'Angola (+244)', country: 'AO' },
  { value: '+245', label: 'Guinea-Bissau (+245)', country: 'GW' },
  { value: '+246', label: 'British Indian Ocean Territory (+246)', country: 'IO' },
  { value: '+248', label: 'Seychelles (+248)', country: 'SC' },
  { value: '+249', label: 'Sudan (+249)', country: 'SD' },
  { value: '+250', label: 'Rwanda (+250)', country: 'RW' },
  { value: '+251', label: 'Ethiopia (+251)', country: 'ET' },
  { value: '+252', label: 'Somalia (+252)', country: 'SO' },
  { value: '+253', label: 'Djibouti (+253)', country: 'DJ' },
  { value: '+254', label: 'Kenya (+254)', country: 'KE' },
  { value: '+255', label: 'Tanzania (+255)', country: 'TZ' },
  { value: '+256', label: 'Uganda (+256)', country: 'UG' },
  { value: '+257', label: 'Burundi (+257)', country: 'BI' },
  { value: '+258', label: 'Mozambique (+258)', country: 'MZ' },
  { value: '+260', label: 'Zambia (+260)', country: 'ZM' },
  { value: '+261', label: 'Madagascar (+261)', country: 'MG' },
  { value: '+262', label: 'Réunion (+262)', country: 'RE' },
  { value: '+263', label: 'Zimbabwe (+263)', country: 'ZW' },
  { value: '+264', label: 'Namibia (+264)', country: 'NA' },
  { value: '+265', label: 'Malawi (+265)', country: 'MW' },
  { value: '+266', label: 'Lesotho (+266)', country: 'LS' },
  { value: '+267', label: 'Botswana (+267)', country: 'BW' },
  { value: '+268', label: 'Swaziland (+268)', country: 'SZ' },
  { value: '+269', label: 'Comoros (+269)', country: 'KM' },
  { value: '+290', label: 'Saint Helena (+290)', country: 'SH' },
  { value: '+291', label: 'Eritrea (+291)', country: 'ER' },
  { value: '+297', label: 'Aruba (+297)', country: 'AW' },
  { value: '+298', label: 'Faroe Islands (+298)', country: 'FO' },
  { value: '+299', label: 'Greenland (+299)', country: 'GL' },
  { value: '+350', label: 'Gibraltar (+350)', country: 'GI' },
  { value: '+351', label: 'Portugal (+351)', country: 'PT' },
  { value: '+352', label: 'Luxembourg (+352)', country: 'LU' },
  { value: '+353', label: 'Ireland (+353)', country: 'IE' },
  { value: '+354', label: 'Iceland (+354)', country: 'IS' },
  { value: '+355', label: 'Albania (+355)', country: 'AL' },
  { value: '+356', label: 'Malta (+356)', country: 'MT' },
  { value: '+357', label: 'Cyprus (+357)', country: 'CY' },
  { value: '+358', label: 'Finland (+358)', country: 'FI' },
  { value: '+359', label: 'Bulgaria (+359)', country: 'BG' },
  { value: '+370', label: 'Lithuania (+370)', country: 'LT' },
  { value: '+371', label: 'Latvia (+371)', country: 'LV' },
  { value: '+372', label: 'Estonia (+372)', country: 'EE' },
  { value: '+373', label: 'Moldova (+373)', country: 'MD' },
  { value: '+374', label: 'Armenia (+374)', country: 'AM' },
  { value: '+375', label: 'Belarus (+375)', country: 'BY' },
  { value: '+376', label: 'Andorra (+376)', country: 'AD' },
  { value: '+377', label: 'Monaco (+377)', country: 'MC' },
  { value: '+378', label: 'San Marino (+378)', country: 'SM' },
  { value: '+380', label: 'Ukraine (+380)', country: 'UA' },
  { value: '+381', label: 'Serbia (+381)', country: 'RS' },
  { value: '+382', label: 'Montenegro (+382)', country: 'ME' },
  { value: '+383', label: 'Kosovo (+383)', country: 'XK' },
  { value: '+385', label: 'Croatia (+385)', country: 'HR' },
  { value: '+386', label: 'Slovenia (+386)', country: 'SI' },
  { value: '+387', label: 'Bosnia and Herzegovina (+387)', country: 'BA' },
  { value: '+389', label: 'North Macedonia (+389)', country: 'MK' },
  { value: '+420', label: 'Czech Republic (+420)', country: 'CZ' },
  { value: '+421', label: 'Slovakia (+421)', country: 'SK' },
  { value: '+423', label: 'Liechtenstein (+423)', country: 'LI' },
  { value: '+500', label: 'Falkland Islands (+500)', country: 'FK' },
  { value: '+501', label: 'Belize (+501)', country: 'BZ' },
  { value: '+502', label: 'Guatemala (+502)', country: 'GT' },
  { value: '+503', label: 'El Salvador (+503)', country: 'SV' },
  { value: '+504', label: 'Honduras (+504)', country: 'HN' },
  { value: '+505', label: 'Nicaragua (+505)', country: 'NI' },
  { value: '+506', label: 'Costa Rica (+506)', country: 'CR' },
  { value: '+507', label: 'Panama (+507)', country: 'PA' },
  { value: '+508', label: 'Saint Pierre and Miquelon (+508)', country: 'PM' },
  { value: '+509', label: 'Haiti (+509)', country: 'HT' },
  { value: '+590', label: 'Guadeloupe (+590)', country: 'GP' },
  { value: '+591', label: 'Bolivia (+591)', country: 'BO' },
  { value: '+592', label: 'Guyana (+592)', country: 'GY' },
  { value: '+593', label: 'Ecuador (+593)', country: 'EC' },
  { value: '+594', label: 'French Guiana (+594)', country: 'GF' },
  { value: '+595', label: 'Paraguay (+595)', country: 'PY' },
  { value: '+596', label: 'Martinique (+596)', country: 'MQ' },
  { value: '+597', label: 'Suriname (+597)', country: 'SR' },
  { value: '+598', label: 'Uruguay (+598)', country: 'UY' },
  { value: '+599', label: 'Netherlands Antilles (+599)', country: 'AN' },
  { value: '+670', label: 'East Timor (+670)', country: 'TL' },
  { value: '+672', label: 'Antarctica (+672)', country: 'AQ' },
  { value: '+673', label: 'Brunei (+673)', country: 'BN' },
  { value: '+674', label: 'Nauru (+674)', country: 'NR' },
  { value: '+675', label: 'Papua New Guinea (+675)', country: 'PG' },
  { value: '+676', label: 'Tonga (+676)', country: 'TO' },
  { value: '+677', label: 'Solomon Islands (+677)', country: 'SB' },
  { value: '+678', label: 'Vanuatu (+678)', country: 'VU' },
  { value: '+679', label: 'Fiji (+679)', country: 'FJ' },
  { value: '+680', label: 'Palau (+680)', country: 'PW' },
  { value: '+681', label: 'Wallis and Futuna (+681)', country: 'WF' },
  { value: '+682', label: 'Cook Islands (+682)', country: 'CK' },
  { value: '+683', label: 'Niue (+683)', country: 'NU' },
  { value: '+684', label: 'American Samoa (+684)', country: 'AS' },
  { value: '+685', label: 'Samoa (+685)', country: 'WS' },
  { value: '+686', label: 'Kiribati (+686)', country: 'KI' },
  { value: '+687', label: 'New Caledonia (+687)', country: 'NC' },
  { value: '+688', label: 'Tuvalu (+688)', country: 'TV' },
  { value: '+689', label: 'French Polynesia (+689)', country: 'PF' },
  { value: '+690', label: 'Tokelau (+690)', country: 'TK' },
  { value: '+691', label: 'Micronesia (+691)', country: 'FM' },
  { value: '+692', label: 'Marshall Islands (+692)', country: 'MH' },
  { value: '+850', label: 'North Korea (+850)', country: 'KP' },
  { value: '+852', label: 'Hong Kong (+852)', country: 'HK' },
  { value: '+853', label: 'Macau (+853)', country: 'MO' },
  { value: '+855', label: 'Cambodia (+855)', country: 'KH' },
  { value: '+856', label: 'Laos (+856)', country: 'LA' },
  { value: '+880', label: 'Bangladesh (+880)', country: 'BD' },
  { value: '+886', label: 'Taiwan (+886)', country: 'TW' },
  { value: '+960', label: 'Maldives (+960)', country: 'MV' },
  { value: '+961', label: 'Lebanon (+961)', country: 'LB' },
  { value: '+962', label: 'Jordan (+962)', country: 'JO' },
  { value: '+963', label: 'Syria (+963)', country: 'SY' },
  { value: '+964', label: 'Iraq (+964)', country: 'IQ' },
  { value: '+965', label: 'Kuwait (+965)', country: 'KW' },
  { value: '+966', label: 'Saudi Arabia (+966)', country: 'SA' },
  { value: '+967', label: 'Yemen (+967)', country: 'YE' },
  { value: '+968', label: 'Oman (+968)', country: 'OM' },
  { value: '+970', label: 'Palestine (+970)', country: 'PS' },
  { value: '+971', label: 'United Arab Emirates (+971)', country: 'AE' },
  { value: '+972', label: 'Israel (+972)', country: 'IL' },
  { value: '+973', label: 'Bahrain (+973)', country: 'BH' },
  { value: '+974', label: 'Qatar (+974)', country: 'QA' },
  { value: '+975', label: 'Bhutan (+975)', country: 'BT' },
  { value: '+976', label: 'Mongolia (+976)', country: 'MN' },
  { value: '+977', label: 'Nepal (+977)', country: 'NP' },
  { value: '+992', label: 'Tajikistan (+992)', country: 'TJ' },
  { value: '+993', label: 'Turkmenistan (+993)', country: 'TM' },
  { value: '+994', label: 'Azerbaijan (+994)', country: 'AZ' },
  { value: '+995', label: 'Georgia (+995)', country: 'GE' },
  { value: '+996', label: 'Kyrgyzstan (+996)', country: 'KG' },
  { value: '+998', label: 'Uzbekistan (+998)', country: 'UZ' }
]

// Helper function to search country codes
export function searchCountryCodes(query) {
  if (!query) return COUNTRY_CODES
  
  const lowercaseQuery = query.toLowerCase()
  return COUNTRY_CODES.filter(country => 
    country.label.toLowerCase().includes(lowercaseQuery) ||
    country.country.toLowerCase().includes(lowercaseQuery) ||
    country.value.includes(query)
  )
}

// Get popular country codes (commonly used ones)
export const POPULAR_COUNTRY_CODES = [
  { value: '+91', label: 'India (+91)', country: 'IN' },
  { value: '+1', label: 'United States (+1)', country: 'US' },
  { value: '+44', label: 'United Kingdom (+44)', country: 'GB' },
  { value: '+971', label: 'United Arab Emirates (+971)', country: 'AE' },
  { value: '+61', label: 'Australia (+61)', country: 'AU' },
  { value: '+86', label: 'China (+86)', country: 'CN' },
  { value: '+81', label: 'Japan (+81)', country: 'JP' },
  { value: '+49', label: 'Germany (+49)', country: 'DE' },
  { value: '+33', label: 'France (+33)', country: 'FR' },
  { value: '+39', label: 'Italy (+39)', country: 'IT' }
]
